speech_config:
  sample_rate: 16000
  frame_ms: 25
  stride_ms: 10
  num_feature_bins: 80
  feature_type: log_mel_spectrogram
  preemphasis: 0.97
  normalize_signal: True
  normalize_feature: True
  normalize_per_feature: False

decoder_config:
  vocabulary: null
  blank_at_zero: False
  beam_width: 500
  lm_config:
    model_path: null
    alpha: 2.0
    beta: 1.0

model_config:
  name: jasper
  dense: True
  first_additional_block_channels: 256
  first_additional_block_kernels: 11
  first_additional_block_strides: 2
  first_additional_block_dilation: 1
  first_additional_block_dropout: 0.2
  nsubblocks: 3
  block_channels: [256, 384, 512, 640, 768]
  block_kernels: [11, 13, 17, 21, 25]
  block_dropout: [0.2, 0.2, 0.2, 0.3, 0.3]
  second_additional_block_channels: 896
  second_additional_block_kernels: 1
  second_additional_block_strides: 1
  second_additional_block_dilation: 2
  second_additional_block_dropout: 0.4
  third_additional_block_channels: 1024
  third_additional_block_kernels: 1
  third_additional_block_strides: 1
  third_additional_block_dilation: 1
  third_additional_block_dropout: 0.4

learning_config:
  train_dataset_config:
    use_tf: True
    data_paths:
      - /home/ubuntu/transcripts_phone_train.tsv
    shuffle: True
    cache: True
    buffer_size: 100
    drop_remainder: True
    stage: train

  eval_dataset_config:
    use_tf: True
    data_paths:
      - /home/ubuntu/transcripts_phone_dev.tsv
    shuffle: False
    cache: True
    buffer_size: 100
    drop_remainder: True
    stage: eval

  test_dataset_config:
    use_tf: True
    data_paths:
      - /home/ubuntu/transcripts_phone_dev.tsv
    shuffle: False
    cache: True
    buffer_size: 100
    drop_remainder: True
    stage: test

  optimizer_config:
    class_name: adam
    config:
      learning_rate: 0.0001

  running_config:
    batch_size: 16
    num_epochs: 30
    accumulation_steps: 8
    outdir: /home/ubuntu/jasper_kor_phone
    log_interval_steps: 400
    save_interval_steps: 400
    eval_interval_steps: 80000
    checkpoint:
      filepath: /home/ubuntu/jasper_kor_phone/checkpoints/{epoch:02d}.h5
      save_best_only: True
      save_weights_only: False
      save_freq: epoch
    states_dir: /home/ubuntu/jasper_kor_phone/states
    tensorboard:
      log_dir: /home/ubuntu/jasper_kor_phone/tensorboard
      histogram_freq: 1
      write_graph: True
      write_images: True
      update_freq: epoch
      profile_batch: 2