speech_config:
  sample_rate: 16000
  frame_ms: 25
  stride_ms: 10
  num_feature_bins: 80
  feature_type: log_mel_spectrogram
  preemphasis: 0.97
  normalize_signal: True
  normalize_feature: True
  normalize_per_feature: False

decoder_config:
  vocabulary: null
  blank_at_zero: False
  beam_width: 500
  lm_config:
    model_path: null
    alpha: 2.0
    beta: 1.0

model_config:
  name: deepspeech2
  conv_type: conv2d
  conv_kernels: [[11, 41], [11, 21], [11, 11]]
  conv_strides: [[2, 2], [1, 2], [1, 2]]
  conv_filters: [32, 32, 96]
  conv_dropout: 0.1
  rnn_nlayers: 5
  rnn_type: lstm
  rnn_units: 512
  rnn_bidirectional: True
  rnn_rowconv: 0
  rnn_dropout: 0.1
  fc_nlayers: 0
  fc_units: 1024

learning_config:
  train_dataset_config:
    use_tf: True
    data_paths:
      - /home/CORPUS/LibriSpeech_tfasr/train-clean-100/transcripts.tsv
    shuffle: True
    cache: True
    buffer_size: 100
    drop_remainder: True
    stage: train

  eval_dataset_config:
    use_tf: True
    data_paths:
      - /home/CORPUS/LibriSpeech_tfasr/dev-clean/transcripts.tsv
    shuffle: False
    cache: True
    buffer_size: 100
    drop_remainder: True
    stage: eval

  test_dataset_config:
    use_tf: True
    data_paths:
      - /home/CORPUS/LibriSpeech_tfasr/test-clean/transcripts.tsv
    shuffle: False
    cache: True
    buffer_size: 100
    drop_remainder: True
    stage: test

  optimizer_config:
    class_name: adam
    config:
      learning_rate: 0.0001

  running_config:
    batch_size: 1
    num_epochs: 20
    accumulation_steps: 8
    outdir: /home/hosung/deepspeech2_tfasr
    log_interval_steps: 40000
    save_interval_steps: 40000
    eval_interval_steps: 80000
    checkpoint:
      filepath: /home/hosung/deepspeech2_tfasr/checkpoints/{epoch:02d}.h5
      save_best_only: True
      save_weights_only: False
      save_freq: epoch
    states_dir: /home/hosung/deepspeech2_tfasr/states
    tensorboard:
      log_dir: /home/hosung/deepspeech2_tfasr/tensorboard
      histogram_freq: 1
      write_graph: True
      write_images: True
      update_freq: epoch
      profile_batch: 2